### ISSUE TITLE
Add integration with Travis CI

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-schenkh#9]
Please configure integration with TravisCI:
* [x] [Enable repo testing in TravisCI](https://travis-ci.com/kpi-web-guild/django-girls-blog-schenkh)
* [x] Add TravisCI badge (master branch) to `README.md` with a single commit. (click ![Build Status](https://travis-ci.com/kpi-web-guild/django-girls-blog-schenkh.svg?branch=master) next to octocat icon on [this page](https://travis-ci.com/kpi-web-guild/django-girls-blog-schenkh))
* [x] Create new branch called `feature/travis-ci-integration` and do all the following steps within that branch.
* [x] Add `.travis.yml` using `pre-commit` as a script. Set it up to run Python 3.7 env and add PIP caching. Ensure you install `pre-commit` before running tests:
```yaml
language: python
python: 3.7
cache: pip
before_install: python -m pip install -U pre-commit
script: python -m pre_commit run --all-files
```
* [x] Push the branch and create a Pull Request for it.
